apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
  creationTimestamp: "2020-04-09T07:34:43Z"
  generation: 11
  labels:
    app: thales-server
  name: thales-server
  namespace: thales
  resourceVersion: "1087251381"
  selfLink: /apis/extensions/v1beta1/namespaces/thales/deployments/thales-server
  uid: 53c5eb2b-5bd6-4577-9c85-678563c9e6a3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: thales-server
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: thales-server
    spec:
      containers:
      - command:
        - thales
        image: thales:dev-v1.3
        imagePullPolicy: IfNotPresent
        name: thales-server
        ports:
        - containerPort: 1024
          hostPort: 1024
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        thales: node
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: thales-server
      serviceAccountName: thales-server
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-04-27T06:54:19Z"
    lastUpdateTime: "2020-04-27T06:54:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-04-20T10:53:40Z"
    lastUpdateTime: "2020-04-27T06:54:19Z"
    message: ReplicaSet "thales-server-6495996d5d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 11
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
